language: rust

os:
- linux
- osx

env:
  global:
    secure: uvkb+H3UozoaxhNVygf/spMqB1LlFY5dwhvZH54bxeV0is/71C7NoENUjkgVzfRxnPnTblwNnaTL02USr2NLMFayFwpzpeOAzJ2pbRQ6YmnsaiLCh+I+Rk/m831mBfHFyEJ0fvmyqj8Mh2Kz1aq8UG62IsSxzbqI9mdhfLnWSj/0+bcIZ108YQpxR8G4CzUPcgeFw1eJF2icZ3Bhn25L6Kb2dQcYMIiw5X+L3OKbDESSzolDUkUwxCpmGUdE/+ROTYESY7n4ehCUih4667WSvIZxbF58lh+PGI8tqA3vtPlw3LswjZI6YM+P0y41A1KmF8JvfBA0yAuDxBI5Y/3/FQqazxfTpDDWtN2ZgBp5jGzk0kwdEAyoZrkE/T5SWx9b/bLQ1rW+3xjtiDh3+9BZ1BYYpZrM9rI3PD3I9prxyZskwFxf3RBImi50JK8YrNTAtpKTT/a7CTzIP9ktzTBfnZDAa1WBm2E85/7AM599zbDfAe+kR67yksYiKJvdxM6LCh5zFl5dtVYphbO2A/czxAO7GpwK+tkh2U/kZvrhHsLP+abMMt3hXtl7x7EkedttLsF/WB2nNRnr6yr7BEJWByPkflzxuJFPMTTLywfl9V70m+SDNzHQZ59a6dn2nbk8sWzsgZU5GbymmQGtR7JGZUo39FCyqQS9ygRw32jGXv0=

cache: cargo

matrix:
  allow_failures:
  - rust: nightly

rust:
- stable
- beta
- nightly

script:
- cargo build --verbose
- cargo test --verbose
